=== larahsan/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
	xmlns="http://www.uniovi.es" 
	elementFormDefault="qualified" 
	targetNamespace="http://www.uniovi.es"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datos" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ref" />
				<xs:element ref="galería" />
				<xs:element ref="coordenadas" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="datos">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="nombre" type="xs:string" use="required" />
					<xs:attribute name="longitudCircuito" type="xs:int" use="required" />
					<xs:attribute name="anchuraMedia" type="xs:int" use="required" />
					<xs:attribute name="fechaCarrera24" type="xs:date" use="required" />
					<xs:attribute name="horaEspInicio" type="xs:time" use="required" />
					<xs:attribute name="numVueltas" type="xs:int" use="required" />
					<xs:attribute name="localidad" type="xs:string" use="required" />
					<xs:attribute name="país" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref" type="xs:string"/>
	<xs:element name="galería">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="3" ref="vídeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="vídeo" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					
					<xs:attribute name="longitud" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value ="-180"/>
								<xs:maxInclusive value ="180"/> 
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					
					<xs:attribute name="latitud" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value ="-90"/>
								<xs:maxInclusive value ="90"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					
					<xs:attribute name="altitud" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value ="0"/>
								<xs:maxInclusive value ="8000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="coordenadas" />
			</xs:sequence>
			<xs:attribute name="distancia" type="xs:int" use="required" />
			<xs:attribute name="numSector" type="xs:int" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== larahsan/SEW/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<circuito 
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <datos 
        nombre="Circuito Internacional de Shanghai" 
        longitudCircuito="5451" 
        anchuraMedia="13" 
        fechaCarrera24="2024-04-21" 
        horaEspInicio="09:00:00" 
        numVueltas="56" 
        localidad="Jiading, Shanghai" 
        país="China"
    />

    <ref>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Shangh%C3%A1i</ref>
    <ref>https://es.wikipedia.org/wiki/Anexo:Gran_Premio_de_China_de_2024</ref>
    <ref>https://lebalap.academy/f1/circuito-internacional-de-shanghai/</ref>
    <ref>https://latitude.to/articles-by-country/cn/china/6987/shanghai-international-circuit</ref>

    <galería>

        <foto>CircuitoDibujo.jpg</foto>
        <foto>CircuitoLineaSalida.jpg</foto>
        <foto>CircuitoPanorama.jpg</foto>

        <vídeo>"ParrillaSalida24.mp4"</vídeo>
        <vídeo>"VueltaCircuito.mp4"</vídeo>

    </galería>

    <coordenadas
        longitud="121.218499126"
        latitud="31.33666532"
        altitud="4"
    />

    <tramo
        distancia="373" 
        numSector="1">

        <coordenadas
            longitud="121.216597"
            latitud="31.336757"
            altitud="3.11"
        />
    </tramo>

    <tramo
        distancia="124" 
        numSector="2">

        <coordenadas
            longitud="121.216291"
            latitud="31.337989"
            altitud="4.12"
        />
    </tramo>

    <tramo
        distancia="99" 
        numSector="3">

        <coordenadas
            longitud="121.217175"
            latitud="31.337866"
            altitud="1.97"
        />
    </tramo>

    <tramo
        distancia="87" 
        numSector="4">

        <coordenadas
            longitud="121.217229"
            latitud="31.337203"
            altitud="1.96"
        />
    </tramo>

    <tramo
        distancia="98" 
        numSector="5">

        <coordenadas
            longitud="121.217806"
            latitud="31.337989"
            altitud="2.36"
        />
    </tramo>

    <tramo
        distancia="319" 
        numSector="6">

        <coordenadas
            longitud="121.215785"
            latitud="31.340085"
            altitud="4.07"
        />
    </tramo>

    <tramo
        distancia="200" 
        numSector="7">

        <coordenadas
            longitud="121.215082"
            latitud="31.342181"
            altitud="4.37"
        />
    </tramo>

    <tramo
        distancia="500" 
        numSector="8">

        <coordenadas
            longitud="121.218185"
            latitud="31.339531"
            altitud="3.95"
        />
    </tramo>

    <tramo
        distancia="300" 
        numSector="9">

        <coordenadas
            longitud="121.220639"
            latitud="31.341349"
            altitud="4.4"
        />
    </tramo>

    <tramo
        distancia="100" 
        numSector="10">

        <coordenadas
            longitud="121.221866"
            latitud="31.340178"
            altitud="4.78"
        />
    </tramo>

    <tramo
        distancia="100" 
        numSector="11">

        <coordenadas
            longitud="121.222660"
            latitud="31.340856"
            altitud="4.7"
        />
    </tramo>

    <tramo
        distancia="500" 
        numSector="12">

        <coordenadas
            longitud="121.220116"
            latitud="31.344493"
            altitud="3.35"
        />
    </tramo>

    <tramo
        distancia="100" 
        numSector="13">

        <coordenadas
            longitud="121.219178"
            latitud="31.344200"
            altitud="3.2"
        />
    </tramo>

    <tramo
        distancia="100" 
        numSector="14">

        <coordenadas
            longitud="121.219160"
            latitud="31.345387"
            altitud="4.06"
        />
    </tramo>

    <tramo
        distancia="200" 
        numSector="15">

        <coordenadas
            longitud="121.220802"
            latitud="31.345171"
            altitud="4.24"
        />
    </tramo>

    <tramo
        distancia="1200" 
        numSector="16">

        <coordenadas
            longitud="121.227929"
            latitud="31.336001"
            altitud="5.18"
        />
    </tramo>

    <tramo
        distancia="100" 
        numSector="17">

        <coordenadas
            longitud="121.227135"
            latitud="31.336094"
            altitud="4.39"
        />
    </tramo>

    <tramo
        distancia="300" 
        numSector="18">

        <coordenadas
            longitud="121.225204"
            latitud="31.338298"
            altitud="4.39"
        />
    </tramo>

    <tramo
        distancia="500" 
        numSector="19">

        <coordenadas
            longitud="121.220711"
            latitud="31.337358"
            altitud="4.13"
        />
    </tramo>

    <tramo
        distancia="402" 
        numSector="20">

        <coordenadas
            longitud="121.216597"
            latitud="31.336757"
            altitud="3.14"
        />
    </tramo>

</circuito>
