=== larahsan/SEW/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (info, tiempo, localizacion, hito+, referencia+, kml, svg)>

<!ELEMENT info (#PCDATA)>
<!ATTLIST info 
    nombre CDATA #REQUIRED
    tipo CDATA #REQUIRED
    descripcion CDATA #REQUIRED
    transporte CDATA #REQUIRED
    agencia CDATA #REQUIRED
    personasAdecuadas CDATA #REQUIRED
    recomendacion CDATA #REQUIRED>

<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo 
    fecha CDATA #IMPLIED
    hora CDATA #IMPLIED
    duracion CDATA #REQUIRED>

<!ELEMENT coordenadas (#PCDATA)>
<!ATTLIST coordenadas 
    longitud CDATA #REQUIRED
    latitud CDATA #REQUIRED
    altitud CDATA #REQUIRED>

<!ELEMENT localizacion (coordenadas)>
<!ATTLIST localizacion 
    lugar CDATA #REQUIRED
    direccion CDATA #REQUIRED>

<!ELEMENT hito (coordenadas, distanciaDesdeHito, galeriaHito)>
<!ATTLIST hito 
    nombreHito CDATA #REQUIRED
    descripcionHito CDATA #REQUIRED>
<!ELEMENT distanciaDesdeHito (#PCDATA)>
<!ATTLIST distanciaDesdeHito 
    unidades CDATA #REQUIRED>
<!ELEMENT galeriaHito (foto+, video*)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT referencia (#PCDATA)>

<!ELEMENT kml (#PCDATA)>
<!ELEMENT svg (#PCDATA)>

=== larahsan/SEW/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Para validar con dtd habría que hacer lo siguiente:
    * Eliminar la primera línea del fichero
    * Añadir esto en su lugar: <!DOCTYPE rutas SYSTEM "rutas.dtd"> 
    * Eliminar los atributos xmlns, xmlns:xsi y xsi:schemaLocation de "rutas" 
-->

<rutas xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta>
        <info 
            nombre="Senda del Oso" 
            tipo="Senderismo"
            descripcion="Pista peatonal y cicloturista habilitada sobre la antigua caja de un ferrocarril minero"
            transporte="A pie o en bicicleta"
            agencia="MaquilAventura (alquier de bicicletas)"
            personasAdecuadas="Todos"
            recomendacion="10"
        />

        <tiempo
            duracion="8 horas"
        />

        <localizacion
            lugar="Area recreativa de Tuñon"
            direccion="Tuñon, Asturias">

            <coordenadas
                longitud="-5.9831974"
                latitud="43.2942007"
                altitud="144.6635760"
            />
        </localizacion>

        <hito
            nombreHito="Desfiladero de las Xanas"
            descripcionHito="Monumento natural">

            <coordenadas 
                longitud="-5.9915034"
                latitud="43.2778461" 
                altitud="176.8771167">
            </coordenadas>
        
            <distanciaDesdeHito
                unidades="1937.21"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta1_SendaOso/Hito1_DesfiladeroXanas.jpg</foto>
                <video>multimedia/videos/Ruta1_Hito1_DesfiladeroXanas.mp4</video>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Area Recreativa de Buyera"
            descripcionHito="Area recreativa con piscina">

            <coordenadas 
                longitud="-6.0030836"
                latitud="43.2630167" 
                altitud="183.3392121">
            </coordenadas>
        
            <distanciaDesdeHito
                unidades="1892.55"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta1_SendaOso/Hito2_Buyera.jpg</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Cercado de osas"
            descripcionHito="Area donde se pueden ver los osos">

            <coordenadas 
                longitud="-6.0051840"
                latitud="43.2578451" 
                altitud="200.3455615">
            </coordenadas>
        
            <distanciaDesdeHito
                unidades="598.13"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta1_SendaOso/Hito3_Osas.jpg</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Desfiladero de PeñasJuntas"
            descripcionHito="Dos paredes de roca vertical muy juntas">
        
            <coordenadas 
                longitud="-6.0358814"
                latitud="43.2306637" 
                altitud="236.7933025">
            </coordenadas>

            <distanciaDesdeHito
                unidades="3908.94"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta1_SendaOso/Hito4_PeñasJuntas.jpg</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Desfiladero de Valdecerezales"
            descripcionHito="Tuneles estrechos">
        
            <coordenadas 
                longitud="-6.0834632"
                latitud="43.1778536" 
                altitud="442.3508823">
            </coordenadas>

            <distanciaDesdeHito
                unidades="7026.63"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta1_SendaOso/Hito5_Valdecerezales.jpg</foto>
            </galeriaHito>
        </hito>

        <referencia>https://www.tevergaturismo.es/rutas-y-sendas/</referencia>
        <referencia>https://www.alltrails.com/es/spain/asturias/teverga</referencia>
        <referencia>https://es.wikiloc.com/wikiloc/user.do?id=486086</referencia>
        <referencia>https://cieloastur.com/actividades/senda-del-oso/#Puntos_de_Interes</referencia>
    
        <kml>xml/kml/ruta1.kml</kml>
        <svg>xml/svg/altimetria1.svg</svg>
    </ruta>

    <ruta>
        <info 
            nombre="Puertos de Marabio" 
            tipo="Senderismo"
            descripcion="Ruta circular por una extensa pradería de montaña"
            transporte="A pie"
            agencia="Sin agencia"
            personasAdecuadas="Todos, recomendado para niños"
            recomendacion="9"
        />

        <tiempo
            duracion="2 horas 30 minutos"
        />

        <localizacion
            lugar="Ermita de Santa Ana"
            direccion="Ermita de Santa Ana, Teverga, Asturias">

            <coordenadas
                longitud="-6.1115043"
                latitud="43.1992751"
                altitud="995.5247216"
            />
        </localizacion>

        <hito
            nombreHito="Fuente"
            descripcionHito="Fuente de agua potable">
        
            <coordenadas 
                longitud="-6.1186111"
                latitud="43.2011690" 
                altitud="983.4061311">
            </coordenadas>

            <distanciaDesdeHito
                unidades="613.39"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta2_Marabio/Hito1_Fuente.jpg</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Pico Caldoveiro"
            descripcionHito="Vistas al Pico Caldoveiro">

            <coordenadas 
                longitud="-6.1191928"
                latitud="43.2175067" 
                altitud="1052.3946822">
            </coordenadas>
        
            <distanciaDesdeHito
                unidades="1816.42"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta2_Marabio/Hito2_Caldoveiro.PNG</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Información"
            descripcionHito="Punto de información">
        
            <coordenadas 
                longitud="-6.1134600"
                latitud="43.2172082" 
                altitud="988.1801284">
            </coordenadas>

            <distanciaDesdeHito
                unidades="468.01"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta2_Marabio/Hito3_Info.PNG</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Casa de Don Pablo"
            descripcionHito="Gran cabaña conocida como Casa de Don Pablo">
        
            <coordenadas 
                longitud="-6.1113247"
                latitud="43.2166728" 
                altitud="974.3128216">
            </coordenadas>

            <distanciaDesdeHito
                unidades="183.01"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta2_Marabio/Hito4_CasaDonPablo.jpg</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Puertu de Marabiu"
            descripcionHito="Fin de la ruta">
        
            <coordenadas 
                longitud="-6.1110938"
                latitud="43.1997656" 
                altitud="998.0000232">
            </coordenadas>

            <distanciaDesdeHito
                unidades="1878.32"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta2_Marabio/Hito5_PuertuMarabiu.PNG</foto>
            </galeriaHito>
        </hito>

        <referencia>https://www.tevergaturismo.es/rutas-y-sendas/</referencia>
        <referencia>https://www.tevergaturismo.es/patrimonio-natural/puertos-de-marabio/</referencia>
        <referencia>https://rutasdeasturias.com/descripcion-ruta/ruta-de-los-puertos-de-marabio-pr-as-72/</referencia>
        <referencia>https://es.wikiloc.com/rutas-senderismo/puertos-marabio-pr-as-72-2884721</referencia>
    
        <kml>xml/kml/ruta2.kml</kml>
        <svg>xml/svg/altimetria2.svg</svg>
    </ruta>

    <ruta>
        <info 
            nombre="Las brañas de Vicenturo y Cueiro" 
            tipo="Senderismo"
            descripcion="Donde tradicionalmente pasta durante el verano el ganado de los pueblos de Campiello, Taxa y Urria"
            transporte="A pie"
            agencia="Sin agencia"
            personasAdecuadas="Todos, aunque puede ser difícil para niños"
            recomendacion="9"
        />

        <tiempo
            duracion="4 horas"
        />

        <localizacion
            lugar="Urría"
            direccion="Urría, Teverga, Asturias">

            <coordenadas
                longitud="-6.1570672"
                latitud="43.1747966"
                altitud="891.1833800"
            />
        </localizacion>

        <hito
            nombreHito="Cuadras de la Conca"
            descripcionHito="Cabañas con ganado">
        
            <coordenadas 
                longitud="-6.1597003"
                latitud="43.1813765" 
                altitud="1141.2631048">
            </coordenadas>

            <distanciaDesdeHito
                unidades="766.52"
            />

            <galeriaHito>
                <foto>multimedia/imagenes/Ruta3_Brañas/Hito1_CuadrasConca.webp</foto>
            </galeriaHito>
        </hito>

        <hito
            nombreHito="Vicenturo"
            descripcionHito="Amplia campera con varias cabañas">

            <coordenadas
